apiVersion: v2
name: artifactory-data-cleanup
description: A Helm chart for Artifactory data cleanup
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: cronjob-common
    version: 0.1.0
    repository: file://../cronjob-common
