apiVersion: v2
name: artifactory-oss
description: A Helm chart for Artifactory OSS
type: application
version: 0.1.0
appVersion: "7.84.23"

dependencies:
  - name: artifactory-common
    version: 0.1.0
    repository: file://../../common
