apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "tekton-pipelinerun-cleanup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tekton-pipelinerun-cleanup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 1800
  suspend: false
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default 3 }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3300
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 3600
          terminationGracePeriodSeconds: 30
          containers:
            - name: cleanup
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- range $name, $value := .Values.envMap }}
                - name: {{ $name }}
                  value: {{ $value | quote }}
                {{- end }}
              command:
                - /bin/bash
                - -c
              args:
                - {{ .Values.script | quote }}
