{{- $sa := .Values.serviceAccount | default dict -}}
{{- if $sa.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton-pipelinerun-cleanup.serviceAccountName" . }}
  labels:
    {{- include "tekton-pipelinerun-cleanup.labels" . | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ hasKey $sa "automount" | ternary $sa.automount true }}
{{- end }}
