apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-jcr-entrypoint
  labels:
    {{- include "artifactory-jcr.labels" . | nindent 4 }}
data:
  run.sh: |-
    #!/bin/bash

    set -eu

    # Artifactory needs to encrypt sensitive details such as join keys and database passwords, and
    # save those changes on the file system. Since secrets are mounted to read-only volumes, there
    # will be read-only file system errors. To work around this, we don't directly mount secrets to
    # the destinations expected by Artifactory. Rather, we mount them to intermediate volumes and then
    # copy them to the target directories where Artifactory expects them.

    set_file_ownership() {
      local file="$1"
      chmod 600 "${file}"
      chown "${JF_ARTIFACTORY_USER}":"${JF_ARTIFACTORY_USER}" "${file}"
    }

    copy_keys() {
      local system_name="$1"

      local security_dir="${JF_PRODUCT_HOME}"/var/etc/security

      mkdir -p "${security_dir}"

      local join_key="${security_dir}"/join.key
      cp /run/secrets/artifactory/"${system_name}"/join.key "${join_key}"
      $(set_file_ownership "${join_key}")

      local master_key="${security_dir}"/master.key
      cp /run/secrets/artifactory/"${system_name}"/master.key "${master_key}"
      $(set_file_ownership "${master_key}")
    }

    copy_system_yaml() {
      local system_name="$1"

      local etc_dir="${JF_PRODUCT_HOME}"/var/etc

      mkdir -p "${etc_dir}"

      cp /run/secrets/artifactory/"${system_name}"/system.yaml "${etc_dir}"/system.yaml
    }

    copy_bootstrap_creds() {
      local access_dir="${JF_PRODUCT_HOME}"/var/etc/access

      mkdir -p "${access_dir}"

      local bootstrap_creds="${access_dir}"/bootstrap.creds

      cp /run/secrets/artifactory/access/bootstrap.creds "${bootstrap_creds}"

      chmod 600 "${bootstrap_creds}"
      chown "${JF_ARTIFACTORY_USER}":"${JF_ARTIFACTORY_USER}" "${bootstrap_creds}"
    }

    copy_keys "jcr"
    copy_system_yaml "jcr"
    copy_bootstrap_creds
    /entrypoint-artifactory.sh

