apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "artifactory-oss-trash-cleanup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "artifactory-oss-trash-cleanup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 1800
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3300
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          terminationGracePeriodSeconds: 30
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | default dict | nindent 12 }}
          containers:
            - name: cleanup
              securityContext:
                {{- toYaml .Values.securityContext | default dict | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: ART_OSS_URL
                  value: {{ .Values.artOssUrl | quote }}
                {{- range $name, $value := .Values.envMap }}
                - name: {{ $name }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- with .Values.envSecrets }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              command: ["/bin/sh", "-c"]
              args:
                - {{ .Values.script | quote }}
