apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifactory-jcr.fullname" . }}
  labels:
    {{- include "artifactory-jcr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: artjcrport
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: artjcrport
  selector:
    {{- include "artifactory-jcr.selectorLabels" . | nindent 4 }}
