apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "artifactory-data-cleanup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "artifactory-data-cleanup.labels" . | nindent 4 }}
