apiVersion: v2
name: chart-repository
description: A Helm chart that fetches source code from Flux, packages internal Helm charts, and serves them via Nginx.
type: application
version: 0.1.0
appVersion: "1.30.2"
